name: CI

on: [ push, pull_request ]

jobs:
  windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-cache-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-cache-
    - run: choco install innosetup
    - run: choco install resourcehacker.portable
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: temurin
    - name: build
      run: mvn verify -B
    - name: x64
      shell: bash
      run: ./build-win64.sh
    - name: x86
      shell: bash
      run: ./build-win32.sh
    - uses: actions/upload-artifact@v3
      with:
        name: windows-amd64
        path: RuneLiteSetup.exe
        retention-days: 1
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: windows-x86
        path: RuneLiteSetup32.exe
        retention-days: 1
        if-no-files-found: error
  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-cache-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-cache-
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: temurin
    - name: build
      run: mvn verify -B
    - name: linux-x64
      run: ./build-linux-x86_64.sh
    - name: linux-aarch64
      run: ./build-linux-aarch64.sh
    - uses: actions/upload-artifact@v3
      with:
        name: jar
        path: target/RuneLite.jar
        retention-days: 1
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: linux-x64
        path: native-linux-x86_64/RuneLite.AppImage
        retention-days: 1
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: linux-aarch64
        path: native-linux-aarch64/RuneLite-aarch64.AppImage
        retention-days: 1
        if-no-files-found: error